package IRCTC;

//Importing required modules to the project
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class MainUI extends javax.swing.JFrame {
    
    //The main function of the program / initial of the program
    public MainUI() {
		//Initialize UI and its components
        initComponents();
		
		//Setting icon for the program from the imported project resource
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
		getResource("train.png")));
		
		//Setting background color of the form pane
        getContentPane().setBackground(new Color(20, 20, 20));
        
          this.setShape(new RoundRectangle2D.Double(0, 0, this.size().width, 
		  this.size().height, 20, 20));
          
          cards = (CardLayout)(pnlCards.getLayout());
    }
    
    //We are gonna use this array list as our database/data source for the program
    //List of stored trains
    ArrayList<TrainInfo> trainsList = new ArrayList<>();
    //List of stored users
    ArrayList<UserInfo> usersList = new ArrayList<>();
    //Global variable to manage cards/tabs of the UI
    CardLayout cards;
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _formMover = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        _trainLogo = new javax.swing.JLabel();
        _homeTabBtn = new javax.swing.JLabel();
        _trainsTabBtn = new javax.swing.JLabel();
        _clientsTabBtn = new javax.swing.JLabel();
        _activeTab = new javax.swing.JPanel();
        _aboutTabBtn = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        __homeTab = new javax.swing.JPanel();
        _homeTabBtn1 = new javax.swing.JLabel();
        _liveFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        _liveTo = new javax.swing.JTextField();
        _liveDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        classCb = new javax.swing.JComboBox<>();
        termsConditionsCb = new javax.swing.JCheckBox();
        findTrainsBtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        _homeTabBtn2 = new javax.swing.JLabel();
        _homeTabBtn3 = new javax.swing.JLabel();
        _homeTabBtn4 = new javax.swing.JLabel();
        _activeTab1 = new javax.swing.JPanel();
        _trainLogo1 = new javax.swing.JLabel();
        _trainLogo2 = new javax.swing.JLabel();
        _trainLogo3 = new javax.swing.JLabel();
        _trainLogo4 = new javax.swing.JLabel();
        _trainLogo5 = new javax.swing.JLabel();
        _homeTabBtn5 = new javax.swing.JLabel();
        _homeTabBtn6 = new javax.swing.JLabel();
        _homeTabBtn7 = new javax.swing.JLabel();
        _homeTabBtn8 = new javax.swing.JLabel();
        _homeTabBtn9 = new javax.swing.JLabel();
        _homeTabBtn10 = new javax.swing.JLabel();
        _homeTabBtn11 = new javax.swing.JLabel();
        _homeTabBtn12 = new javax.swing.JLabel();
        _homeTabBtn13 = new javax.swing.JLabel();
        _homeTabBtn14 = new javax.swing.JLabel();
        __trainsTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        activeTraffic = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        __trainName = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        __startsFrom = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        __destination = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        __timing = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        __ticketPrice = new javax.swing.JTextField();
        removeBtn = new javax.swing.JButton();
        __clientsTab = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        usersListL = new javax.swing.JList<>();
        jLabel26 = new javax.swing.JLabel();
        __userName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        __userEmail = new javax.swing.JTextField();
        addBtn1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        __userPassword = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        __userTicketID = new javax.swing.JTextField();
        addBtn2 = new javax.swing.JButton();
        __aboutTab = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IRCTC Connect v1.0");
        setBackground(new java.awt.Color(20, 20, 20));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        _formMover.setBackground(new java.awt.Color(51, 102, 255));
        _formMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                _formMoverMouseDragged(evt);
            }
        });
        _formMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _formMoverMousePressed(evt);
            }
        });

        javax.swing.GroupLayout _formMoverLayout = new javax.swing.GroupLayout(_formMover);
        _formMover.setLayout(_formMoverLayout);
        _formMoverLayout.setHorizontalGroup(
            _formMoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        _formMoverLayout.setVerticalGroup(
            _formMoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jSplitPane1.setBackground(new java.awt.Color(20, 20, 20));
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(0);

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));

        _trainLogo.setBackground(new java.awt.Color(20, 20, 20));
        _trainLogo.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _trainLogo.setForeground(new java.awt.Color(0, 153, 255));
        _trainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _trainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IRCTC/trainLogo.png"))); // NOI18N
        _trainLogo.setAlignmentY(0.0F);

        _homeTabBtn.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _homeTabBtn.setForeground(new java.awt.Color(0, 153, 255));
        _homeTabBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn.setText("Home");
        _homeTabBtn.setAlignmentY(0.0F);
        _homeTabBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _homeTabBtnMouseClicked(evt);
            }
        });

        _trainsTabBtn.setBackground(new java.awt.Color(20, 20, 20));
        _trainsTabBtn.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _trainsTabBtn.setForeground(new java.awt.Color(0, 153, 255));
        _trainsTabBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _trainsTabBtn.setText("Trains");
        _trainsTabBtn.setAlignmentY(0.0F);
        _trainsTabBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _trainsTabBtnMouseClicked(evt);
            }
        });

        _clientsTabBtn.setBackground(new java.awt.Color(20, 20, 20));
        _clientsTabBtn.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _clientsTabBtn.setForeground(new java.awt.Color(0, 153, 255));
        _clientsTabBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _clientsTabBtn.setText("Clients");
        _clientsTabBtn.setAlignmentY(0.0F);
        _clientsTabBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _clientsTabBtnMouseClicked(evt);
            }
        });

        _activeTab.setBackground(new java.awt.Color(0, 153, 255));
        _activeTab.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout _activeTabLayout = new javax.swing.GroupLayout(_activeTab);
        _activeTab.setLayout(_activeTabLayout);
        _activeTabLayout.setHorizontalGroup(
            _activeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        _activeTabLayout.setVerticalGroup(
            _activeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _aboutTabBtn.setBackground(new java.awt.Color(20, 20, 20));
        _aboutTabBtn.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _aboutTabBtn.setForeground(new java.awt.Color(0, 153, 255));
        _aboutTabBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _aboutTabBtn.setText("About");
        _aboutTabBtn.setAlignmentY(0.0F);
        _aboutTabBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _aboutTabBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(_trainLogo)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(_activeTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_aboutTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_clientsTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_trainsTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_homeTabBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(_trainLogo)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_activeTab, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(_homeTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(_trainsTabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(_clientsTabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(_aboutTabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        pnlCards.setBackground(new java.awt.Color(20, 20, 20));
        pnlCards.setLayout(new java.awt.CardLayout());

        __homeTab.setBackground(new java.awt.Color(20, 20, 20));

        _homeTabBtn1.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        _homeTabBtn1.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn1.setText("Hard to manage clients and trains ?");
        _homeTabBtn1.setAlignmentY(0.0F);

        _liveFrom.setBackground(new java.awt.Color(20, 20, 20));
        _liveFrom.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _liveFrom.setForeground(new java.awt.Color(0, 153, 255));
        _liveFrom.setToolTipText("Enter your email address");
        _liveFrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        _liveFrom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 70, 70));
        jLabel3.setText("From");
        jLabel3.setAlignmentY(0.0F);

        jLabel4.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 70, 70));
        jLabel4.setText("To");
        jLabel4.setAlignmentY(0.0F);

        _liveTo.setBackground(new java.awt.Color(20, 20, 20));
        _liveTo.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _liveTo.setForeground(new java.awt.Color(0, 153, 255));
        _liveTo.setToolTipText("Enter your email address");
        _liveTo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        _liveDate.setBackground(new java.awt.Color(20, 20, 20));
        _liveDate.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _liveDate.setForeground(new java.awt.Color(0, 153, 255));
        _liveDate.setToolTipText("Enter your email address");
        _liveDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        jLabel5.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 70, 70));
        jLabel5.setText("Date");
        jLabel5.setAlignmentY(0.0F);

        classCb.setBackground(new java.awt.Color(20, 20, 20));
        classCb.setFont(new java.awt.Font("Visby Round CF", 0, 12)); // NOI18N
        classCb.setForeground(new java.awt.Color(0, 153, 255));
        classCb.setMaximumRowCount(16);
        classCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC Executive Chair Class (EC)", "AC First Class (1AC)", "AC Two-Tier Class (2AC)", "AC Three-Tier Class (3AC)", "First Class (FC)", "AC Chair Class (CC)", "Sleeper Class (SL)", "Second Class (2S)" }));
        classCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        termsConditionsCb.setFont(new java.awt.Font("Visby Round CF", 0, 12)); // NOI18N
        termsConditionsCb.setForeground(new java.awt.Color(0, 153, 255));
        termsConditionsCb.setText("I agree to Terms and Conditions");
        termsConditionsCb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                termsConditionsCbStateChanged(evt);
            }
        });

        findTrainsBtn.setBackground(new java.awt.Color(0, 153, 255));
        findTrainsBtn.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        findTrainsBtn.setForeground(new java.awt.Color(0, 153, 255));
        findTrainsBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        findTrainsBtn.setText("Find Trains");
        findTrainsBtn.setAlignmentY(0.0F);
        findTrainsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        findTrainsBtn.setEnabled(false);
        findTrainsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findTrainsBtnMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 70, 70));
        jLabel6.setText("Enjoy Loyalty program's benifits by linking IRCTC SBI Card with");
        jLabel6.setAlignmentY(0.0F);

        jLabel7.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 70, 70));
        jLabel7.setText("your IRCTC User ID");
        jLabel7.setAlignmentY(0.0F);

        _homeTabBtn2.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn2.setFont(new java.awt.Font("Visby Round CF", 1, 18)); // NOI18N
        _homeTabBtn2.setForeground(new java.awt.Color(0, 153, 255));
        _homeTabBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn2.setText("Find Trains Live");
        _homeTabBtn2.setAlignmentY(0.0F);

        _homeTabBtn3.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        _homeTabBtn3.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn3.setText("Unable to manage your service ?");
        _homeTabBtn3.setAlignmentY(0.0F);

        _homeTabBtn4.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        _homeTabBtn4.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn4.setText("Try any management feature");
        _homeTabBtn4.setAlignmentY(0.0F);

        _activeTab1.setBackground(new java.awt.Color(255, 255, 255));
        _activeTab1.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout _activeTab1Layout = new javax.swing.GroupLayout(_activeTab1);
        _activeTab1.setLayout(_activeTab1Layout);
        _activeTab1Layout.setHorizontalGroup(
            _activeTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );
        _activeTab1Layout.setVerticalGroup(
            _activeTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        _trainLogo1.setBackground(new java.awt.Color(20, 20, 20));
        _trainLogo1.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _trainLogo1.setForeground(new java.awt.Color(0, 153, 255));
        _trainLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _trainLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IRCTC/trafficIcon.png"))); // NOI18N
        _trainLogo1.setAlignmentY(0.0F);

        _trainLogo2.setBackground(new java.awt.Color(20, 20, 20));
        _trainLogo2.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _trainLogo2.setForeground(new java.awt.Color(0, 153, 255));
        _trainLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _trainLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IRCTC/trainFrontIcon.png"))); // NOI18N
        _trainLogo2.setAlignmentY(0.0F);

        _trainLogo3.setBackground(new java.awt.Color(20, 20, 20));
        _trainLogo3.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _trainLogo3.setForeground(new java.awt.Color(0, 153, 255));
        _trainLogo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _trainLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IRCTC/customerIcon.png"))); // NOI18N
        _trainLogo3.setAlignmentY(0.0F);

        _trainLogo4.setBackground(new java.awt.Color(20, 20, 20));
        _trainLogo4.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _trainLogo4.setForeground(new java.awt.Color(0, 153, 255));
        _trainLogo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _trainLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IRCTC/infoIcon.png"))); // NOI18N
        _trainLogo4.setAlignmentY(0.0F);

        _trainLogo5.setBackground(new java.awt.Color(20, 20, 20));
        _trainLogo5.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        _trainLogo5.setForeground(new java.awt.Color(0, 153, 255));
        _trainLogo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _trainLogo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IRCTC/dateIcon.png"))); // NOI18N
        _trainLogo5.setAlignmentY(0.0F);

        _homeTabBtn5.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn5.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn5.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn5.setText("Status");
        _homeTabBtn5.setAlignmentY(0.0F);

        _homeTabBtn6.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn6.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn6.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn6.setText("Trains");
        _homeTabBtn6.setAlignmentY(0.0F);

        _homeTabBtn7.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn7.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn7.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn7.setText("Daily");
        _homeTabBtn7.setAlignmentY(0.0F);

        _homeTabBtn8.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn8.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn8.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn8.setText("Traffic");
        _homeTabBtn8.setAlignmentY(0.0F);

        _homeTabBtn9.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn9.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn9.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn9.setText("Reg...");
        _homeTabBtn9.setAlignmentY(0.0F);

        _homeTabBtn10.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn10.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn10.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn10.setText("Clients");
        _homeTabBtn10.setAlignmentY(0.0F);

        _homeTabBtn11.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn11.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn11.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn11.setText("Database");
        _homeTabBtn11.setAlignmentY(0.0F);

        _homeTabBtn12.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn12.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn12.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn12.setText("Info");
        _homeTabBtn12.setAlignmentY(0.0F);

        _homeTabBtn13.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn13.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn13.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn13.setText("Service");
        _homeTabBtn13.setAlignmentY(0.0F);

        _homeTabBtn14.setBackground(new java.awt.Color(20, 20, 20));
        _homeTabBtn14.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        _homeTabBtn14.setForeground(new java.awt.Color(255, 255, 255));
        _homeTabBtn14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _homeTabBtn14.setText("Shedules");
        _homeTabBtn14.setAlignmentY(0.0F);

        javax.swing.GroupLayout __homeTabLayout = new javax.swing.GroupLayout(__homeTab);
        __homeTab.setLayout(__homeTabLayout);
        __homeTabLayout.setHorizontalGroup(
            __homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __homeTabLayout.createSequentialGroup()
                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(findTrainsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classCb, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(__homeTabLayout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __homeTabLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))))
                                .addComponent(_liveFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                                .addComponent(_liveTo)
                                .addComponent(_liveDate)))
                        .addGroup(__homeTabLayout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(termsConditionsCb, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __homeTabLayout.createSequentialGroup()
                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_homeTabBtn1)
                            .addComponent(_homeTabBtn4)
                            .addComponent(_activeTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_homeTabBtn3)
                            .addGroup(__homeTabLayout.createSequentialGroup()
                                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_trainLogo2)
                                    .addGroup(__homeTabLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(_homeTabBtn5)
                                            .addComponent(_homeTabBtn6))))
                                .addGap(73, 73, 73)
                                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_trainLogo1)
                                    .addGroup(__homeTabLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(_homeTabBtn8)
                                            .addComponent(_homeTabBtn7))))
                                .addGap(70, 70, 70)
                                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_trainLogo3)
                                    .addGroup(__homeTabLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(_homeTabBtn10)
                                            .addComponent(_homeTabBtn9))))))
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __homeTabLayout.createSequentialGroup()
                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(__homeTabLayout.createSequentialGroup()
                                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_trainLogo4)
                                    .addComponent(_homeTabBtn11))
                                .addGap(73, 73, 73))
                            .addGroup(__homeTabLayout.createSequentialGroup()
                                .addComponent(_homeTabBtn12)
                                .addGap(105, 105, 105)))
                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_trainLogo5)
                            .addGroup(__homeTabLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(_homeTabBtn13))
                            .addComponent(_homeTabBtn14))
                        .addGap(195, 195, 195))))
            .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(__homeTabLayout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(_homeTabBtn2)
                    .addContainerGap(750, Short.MAX_VALUE)))
        );
        __homeTabLayout.setVerticalGroup(
            __homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(__homeTabLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(_homeTabBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(__homeTabLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_liveFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_liveTo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_liveDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(__homeTabLayout.createSequentialGroup()
                        .addComponent(_homeTabBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_homeTabBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(__homeTabLayout.createSequentialGroup()
                                .addComponent(_activeTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_trainLogo2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __homeTabLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_trainLogo1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(_trainLogo3, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(__homeTabLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(termsConditionsCb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(__homeTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(__homeTabLayout.createSequentialGroup()
                                .addComponent(_homeTabBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_homeTabBtn8))
                            .addGroup(__homeTabLayout.createSequentialGroup()
                                .addComponent(_homeTabBtn6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_homeTabBtn5))
                            .addGroup(__homeTabLayout.createSequentialGroup()
                                .addComponent(_homeTabBtn9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_homeTabBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(__homeTabLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(findTrainsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(__homeTabLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_trainLogo4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(_trainLogo5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_homeTabBtn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_homeTabBtn11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_homeTabBtn12)
                            .addComponent(_homeTabBtn14))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(__homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(__homeTabLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(_homeTabBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(598, Short.MAX_VALUE)))
        );

        pnlCards.add(__homeTab, "HOME");
        __homeTab.getAccessibleContext().setAccessibleName("");

        __trainsTab.setBackground(new java.awt.Color(20, 20, 20));

        activeTraffic.setBackground(new java.awt.Color(25, 25, 25));
        activeTraffic.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        activeTraffic.setForeground(new java.awt.Color(255, 255, 255));
        activeTraffic.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(activeTraffic);

        jLabel20.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(90, 90, 90));
        jLabel20.setText("Train Name");

        __trainName.setBackground(new java.awt.Color(25, 25, 25));
        __trainName.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        __trainName.setForeground(new java.awt.Color(255, 255, 255));
        __trainName.setText("X Express 2");

        addBtn.setBackground(new java.awt.Color(25, 25, 25));
        addBtn.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 153, 255));
        addBtn.setText("Add Train");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 70, 70));
        jLabel8.setText("Active Traffic");

        jLabel21.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(90, 90, 90));
        jLabel21.setText("Starts from");

        __startsFrom.setBackground(new java.awt.Color(25, 25, 25));
        __startsFrom.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        __startsFrom.setForeground(new java.awt.Color(255, 255, 255));
        __startsFrom.setText("Y Place");

        jLabel22.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(90, 90, 90));
        jLabel22.setText("Destination");

        __destination.setBackground(new java.awt.Color(25, 25, 25));
        __destination.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        __destination.setForeground(new java.awt.Color(255, 255, 255));
        __destination.setText("Z Place");

        jLabel23.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(90, 90, 90));
        jLabel23.setText("Date");

        __timing.setBackground(new java.awt.Color(25, 25, 25));
        __timing.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        __timing.setForeground(new java.awt.Color(255, 255, 255));
        __timing.setText("XX/XX/20XX");

        jLabel25.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(90, 90, 90));
        jLabel25.setText("Ticket base price");

        __ticketPrice.setBackground(new java.awt.Color(25, 25, 25));
        __ticketPrice.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        __ticketPrice.setForeground(new java.awt.Color(255, 255, 255));
        __ticketPrice.setText("200");

        removeBtn.setBackground(new java.awt.Color(25, 25, 25));
        removeBtn.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(0, 153, 255));
        removeBtn.setText("Remove selected train");
        removeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout __trainsTabLayout = new javax.swing.GroupLayout(__trainsTab);
        __trainsTab.setLayout(__trainsTabLayout);
        __trainsTabLayout.setHorizontalGroup(
            __trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(__trainsTabLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(__trainsTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __trainsTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(__trainsTabLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(__trainsTabLayout.createSequentialGroup()
                                        .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addGap(52, 52, 52)
                                        .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(__startsFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(__trainName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(__trainsTabLayout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                            .addComponent(__destination, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __trainsTabLayout.createSequentialGroup()
                                            .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel25))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(__ticketPrice)
                                                .addComponent(__timing, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        __trainsTabLayout.setVerticalGroup(
            __trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(__trainsTabLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(__trainsTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                        .addGap(75, 75, 75))
                    .addGroup(__trainsTabLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__trainName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__startsFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__timing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__ticketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(__trainsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlCards.add(__trainsTab, "TRAINS");

        __clientsTab.setBackground(new java.awt.Color(20, 20, 20));

        jLabel17.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(70, 70, 70));
        jLabel17.setText("Registered users");

        usersListL.setBackground(new java.awt.Color(25, 25, 25));
        usersListL.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        usersListL.setForeground(new java.awt.Color(255, 255, 255));
        usersListL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(usersListL);

        jLabel26.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(90, 90, 90));
        jLabel26.setText("Name");

        __userName.setBackground(new java.awt.Color(25, 25, 25));
        __userName.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        __userName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(90, 90, 90));
        jLabel27.setText("Email");

        __userEmail.setBackground(new java.awt.Color(25, 25, 25));
        __userEmail.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        __userEmail.setForeground(new java.awt.Color(255, 255, 255));

        addBtn1.setBackground(new java.awt.Color(25, 25, 25));
        addBtn1.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        addBtn1.setForeground(new java.awt.Color(0, 153, 255));
        addBtn1.setText("Add Entry");
        addBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtn1MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(90, 90, 90));
        jLabel28.setText("Password");

        __userPassword.setBackground(new java.awt.Color(25, 25, 25));
        __userPassword.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        __userPassword.setForeground(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(90, 90, 90));
        jLabel29.setText("Ticket ID");

        __userTicketID.setBackground(new java.awt.Color(25, 25, 25));
        __userTicketID.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        __userTicketID.setForeground(new java.awt.Color(255, 255, 255));

        addBtn2.setBackground(new java.awt.Color(25, 25, 25));
        addBtn2.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        addBtn2.setForeground(new java.awt.Color(0, 153, 255));
        addBtn2.setText("Remove Entry");
        addBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeEntryBtn(evt);
            }
        });

        javax.swing.GroupLayout __clientsTabLayout = new javax.swing.GroupLayout(__clientsTab);
        __clientsTab.setLayout(__clientsTabLayout);
        __clientsTabLayout.setHorizontalGroup(
            __clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(__clientsTabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(__clientsTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __clientsTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(__clientsTabLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(__clientsTabLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(__userTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __clientsTabLayout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(__userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, __clientsTabLayout.createSequentialGroup()
                                        .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27))
                                        .addGap(52, 52, 52)
                                        .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(__userEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(__userName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        __clientsTabLayout.setVerticalGroup(
            __clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(__clientsTabLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(__clientsTabLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__userTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181)
                        .addGroup(__clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );

        pnlCards.add(__clientsTab, "CLIENTS");

        __aboutTab.setBackground(new java.awt.Color(20, 20, 20));

        jLabel9.setFont(new java.awt.Font("Visby Round CF", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("IRCTC Connect");

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Visby Round CF", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("(C)Copyrights 2023 Devil. All rights reserved");

        jLabel11.setFont(new java.awt.Font("Visby Round CF", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("v1.0");

        jLabel12.setFont(new java.awt.Font("Visby Round CF", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("This tool/program doesn't mean to voilate any laws or rules");

        jLabel13.setFont(new java.awt.Font("Visby Round CF", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setText("from IRCTC or any organization and doesn't gurantee any");

        jLabel14.setFont(new java.awt.Font("Visby Round CF", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("official connection from IRCTC servers.");

        jLabel15.setFont(new java.awt.Font("Visby Round CF", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 255));
        jLabel15.setText("JUST A SCHOOL PROJECT :)");

        jLabel16.setFont(new java.awt.Font("Visby Round CF", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 255));
        jLabel16.setText("~Made with love by Devil (Akash Kumar)");

        javax.swing.GroupLayout __aboutTabLayout = new javax.swing.GroupLayout(__aboutTab);
        __aboutTab.setLayout(__aboutTabLayout);
        __aboutTabLayout.setHorizontalGroup(
            __aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(__aboutTabLayout.createSequentialGroup()
                .addGroup(__aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(__aboutTabLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addGroup(__aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(__aboutTabLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel11))))
                    .addGroup(__aboutTabLayout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jLabel10))
                    .addGroup(__aboutTabLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(__aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addGroup(__aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel13))))
                    .addGroup(__aboutTabLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel15)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        __aboutTabLayout.setVerticalGroup(
            __aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(__aboutTabLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(52, 52, 52)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(92, 92, 92)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(48, 48, 48))
        );

        pnlCards.add(__aboutTab, "ABOUT");

        jSplitPane1.setRightComponent(pnlCards);

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IRCTC/crossBtn2.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(_formMover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeBtn)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(_formMover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //event when the window is opened
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
		//GEN-FIRST:event_formWindowOpened
    // TODO add your handling code here:
		
	//Adding some example data (as default data) for tests
        trainsList.add(new TrainInfo("Rajdhani Express", "Mumbai", 
		"Ranchi", "10/2/2023", 500));
        trainsList.add(new TrainInfo("Duronto Express", "Dhanbad", 
		"Bokaro", "14/1/2023", 900));
        trainsList.add(new TrainInfo("Rajdhani Express", "Mumbai", 
		"Ranchi", "7/2/2023", 200));
        
        usersList.add(new UserInfo("Arijit Chandra", "arijitchandra@gmail.com", 
		"Arijit@1234", "XLGD01111XD"));
        usersList.add(new UserInfo("Adarsh", "adjoint22@gmail.com", "adj@11", 
		"BDNFUR8394"));
        usersList.add(new UserInfo("Someone", "someone12@eg.com", "someoneI", 
		"34BHJDSFIO84"));
        
        //Preloading data from database to UI
        LoadTrainsToUI();
        LoadUsersToUI();
		
    }//GEN-LAST:event_formWindowOpened

    //Custom form mover logics
    private void _formMoverMouseDragged(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event__formMoverMouseDragged
        // TODO add your handling code here:
        //Set form location when the custom control is dragged
        setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event__formMoverMouseDragged

    int posX=0,posY=0;
    private void _formMoverMousePressed(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event__formMoverMousePressed
        // TODO add your handling code here:
        //Set last pressed location for logics
        posX=evt.getX();
        posY=evt.getY();
    }//GEN-LAST:event__formMoverMousePressed
    //--Logic Ends
    
    //Changing tabs using cards logic
    private void _homeTabBtnMouseClicked(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event__homeTabBtnMouseClicked
        // TODO add your handling code here:
        _activeTab.setLocation(new Point(0, _homeTabBtn.location().y));
        cards.show(pnlCards, "HOME");
    }//GEN-LAST:event__homeTabBtnMouseClicked

    private void _trainsTabBtnMouseClicked(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event__trainsTabBtnMouseClicked
        // TODO add your handling code here:
        
        _activeTab.setLocation(new Point(0, _trainsTabBtn.location().y));
        cards.show(pnlCards, "TRAINS");
    }//GEN-LAST:event__trainsTabBtnMouseClicked

    private void _clientsTabBtnMouseClicked(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event__clientsTabBtnMouseClicked
        // TODO add your handling code here:
        _activeTab.setLocation(new Point(0, _clientsTabBtn.location().y));
        cards.show(pnlCards, "CLIENTS");
    }//GEN-LAST:event__clientsTabBtnMouseClicked

    private void _aboutTabBtnMouseClicked(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event__aboutTabBtnMouseClicked
        // TODO add your handling code here:
        _activeTab.setLocation(new Point(0, _aboutTabBtn.location().y));
        cards.show(pnlCards, "ABOUT");
    }//GEN-LAST:event__aboutTabBtnMouseClicked
    //--Login ends
    
    //Custom close button
    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    //event when find trains button is clicked
    private void findTrainsBtnMouseClicked(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event_findTrainsBtnMouseClicked
        // TODO add your handling code here:

        //Validating input if blank or not
        if (_liveFrom.getText().isBlank() || _liveTo.getText().isBlank() ||
		_liveDate.getText().isBlank())
        {
            MessageBox("None of the fields can be empty", "Error");
            return;
        }
        
        //validating if terms and conditions are checked or not
        if (!termsConditionsCb.isSelected())
        {
            MessageBox("You must accept our terms and conditions to continue", "Error");
            return;
        }
        
        //getting the train with specified details
        TrainInfo gotTrain = getTrainExist(new TrainInfo("", _liveFrom.getText(),
		_liveTo.getText(), _liveDate.getText(), 0));
        
        //validating if a train is found or not
        if (gotTrain == null)
        {
            MessageBox("No trains found for the selected start and end location !",
			"No trains");
            return;
        }
        
        //Showing trains details after train is found
        MessageBox("Train found for you !\n\nTrain Name : " + gotTrain.Name +
		"\nStarts at : " + gotTrain.StartsFrom + "\nDestination : " +
		gotTrain.Destination + "\nPrice : Rs. " +
		(gotTrain.TicketPrice * (classCb.getSelectedIndex() + 1)),
		"Train found on " + _liveDate.getText());

    }//GEN-LAST:event_findTrainsBtnMouseClicked

    //custom function to get train with specified details
    public TrainInfo getTrainExist(TrainInfo t)
    {
        for (int x=0; x < trainsList.size(); x++)
        {
            if (trainsList.get(x).StartsFrom.toLowerCase().
			startsWith(t.StartsFrom.toLowerCase()) && 
			trainsList.get(x).Destination.toLowerCase().
			startsWith(t.Destination.toLowerCase()) && 
			trainsList.get(x).Timing.toLowerCase().
			startsWith(t.Timing.toLowerCase()))
            {
                return trainsList.get(x);
            }
        }
        
        return null;
    }
    
    //Custom function to show a message dialog
    public void MessageBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, 
		titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    //Enable disable buttons depending of the check box checked or not
    private void termsConditionsCbStateChanged(javax.swing.event.ChangeEvent evt) {
		//GEN-FIRST:event_termsConditionsCbStateChanged
        // TODO add your handling code here:
        if (termsConditionsCb.isSelected())
        {
            findTrainsBtn.setEnabled(true);
        }
        else
        {
            findTrainsBtn.setEnabled(false);
        }
    }//GEN-LAST:event_termsConditionsCbStateChanged

    //Add the specified train details to the database
    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        trainsList.add(new TrainInfo(__trainName.getText(),
		__startsFrom.getText(), __destination.getText(), 
		__timing.getText(), Integer.parseInt(__ticketPrice.getText())));
        LoadTrainsToUI();
    }//GEN-LAST:event_addBtnMouseClicked

    //Add the specified user details to the database
    private void addBtn1MouseClicked(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event_addBtn1MouseClicked
        // TODO add your handling code here:
        usersList.add(new UserInfo(__userName.getText(), 
		__userEmail.getText(), __userPassword.getText(), 
		__userTicketID.getText()));
        LoadUsersToUI();
    }//GEN-LAST:event_addBtn1MouseClicked

    //Remove the selected train from database
    private void removeBtnMouseClicked(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event_removeBtnMouseClicked
        // TODO add your handling code here:
        trainsList.remove(activeTraffic.getSelectedIndex());
        LoadTrainsToUI();
    }//GEN-LAST:event_removeBtnMouseClicked

    //Remove the selected user from the database
    private void removeEntryBtn(java.awt.event.MouseEvent evt) {
		//GEN-FIRST:event_removeEntryBtn
        // TODO add your handling code here:
        usersList.remove(usersListL.getSelectedIndex());
        LoadUsersToUI();
    }//GEN-LAST:event_removeEntryBtn
    
    //Custom function to load trains from database to UI
    public void LoadTrainsToUI()
    {
		//clearning the JList
        activeTraffic.removeAll();
		
		//Declaring a new List Model to set in JList
        DefaultListModel values = new DefaultListModel();
		
		//Iterating through all elements of the database
        for(int i=0; i<trainsList.size(); i++)
        {
			//Adding the names each Patient name from the currrent database
            values.addElement(trainsList.get(i).Name + "           " +
			trainsList.get(i).StartsFrom + "           " +
			trainsList.get(i).Destination + "           " +
			trainsList.get(i).Timing + "           " +
			trainsList.get(i).TicketPrice + " Rs.");
        }
		
		//Setting our declared model to the JList to show in UI
        activeTraffic.setModel(values);
    }
    
    //Custom fucntion to load users from database to UI
    public void LoadUsersToUI()
    {
		//clearning the JList
        usersListL.removeAll();
		
		//Declaring a new List Model to set in JList
        DefaultListModel values = new DefaultListModel();
		
		//Iterating through all elements of the database
        for(int i=0; i<usersList.size(); i++)
        {
			//Adding the names each Patient name from the currrent database
            values.addElement(usersList.get(i).Name + "        " + 
			usersList.get(i).Email + "        " + 
			usersList.get(i).Password + "        " + 
			usersList.get(i).TicketID);
        }
		
		//Setting our declared model to the JList to show in UI
        usersListL.setModel(values);
    }
    
    //Custom class to store values
    public class TrainInfo
    {
        public String Name;
        public String StartsFrom;
        public String Destination;
        public String Timing;
        public int TicketPrice;
        
        TrainInfo(String _name, String _startFrom, 
		String _destination, String _timing, int _ticketPrice)
        {
            Name = _name;
            StartsFrom = _startFrom;
            Destination = _destination;
            Timing = _timing;
            TicketPrice = _ticketPrice;
        }
    }
    public class UserInfo
    {
        public String Name;
        public String Email;
        public String Password;
        public String TicketID;
        
        UserInfo(String _name, String _email, String _password, String _ticketid)
        {
            Name = _name;
            Email = _email;
            Password = _password;
            TicketID = _ticketid;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel __aboutTab;
    private javax.swing.JPanel __clientsTab;
    private javax.swing.JTextField __destination;
    private javax.swing.JPanel __homeTab;
    private javax.swing.JTextField __startsFrom;
    private javax.swing.JTextField __ticketPrice;
    private javax.swing.JTextField __timing;
    private javax.swing.JTextField __trainName;
    private javax.swing.JPanel __trainsTab;
    private javax.swing.JTextField __userEmail;
    private javax.swing.JTextField __userName;
    private javax.swing.JTextField __userPassword;
    private javax.swing.JTextField __userTicketID;
    private javax.swing.JLabel _aboutTabBtn;
    private javax.swing.JPanel _activeTab;
    private javax.swing.JPanel _activeTab1;
    private javax.swing.JLabel _clientsTabBtn;
    private javax.swing.JPanel _formMover;
    private javax.swing.JLabel _homeTabBtn;
    private javax.swing.JLabel _homeTabBtn1;
    private javax.swing.JLabel _homeTabBtn10;
    private javax.swing.JLabel _homeTabBtn11;
    private javax.swing.JLabel _homeTabBtn12;
    private javax.swing.JLabel _homeTabBtn13;
    private javax.swing.JLabel _homeTabBtn14;
    private javax.swing.JLabel _homeTabBtn2;
    private javax.swing.JLabel _homeTabBtn3;
    private javax.swing.JLabel _homeTabBtn4;
    private javax.swing.JLabel _homeTabBtn5;
    private javax.swing.JLabel _homeTabBtn6;
    private javax.swing.JLabel _homeTabBtn7;
    private javax.swing.JLabel _homeTabBtn8;
    private javax.swing.JLabel _homeTabBtn9;
    private javax.swing.JTextField _liveDate;
    private javax.swing.JTextField _liveFrom;
    private javax.swing.JTextField _liveTo;
    private javax.swing.JLabel _trainLogo;
    private javax.swing.JLabel _trainLogo1;
    private javax.swing.JLabel _trainLogo2;
    private javax.swing.JLabel _trainLogo3;
    private javax.swing.JLabel _trainLogo4;
    private javax.swing.JLabel _trainLogo5;
    private javax.swing.JLabel _trainsTabBtn;
    private javax.swing.JList<String> activeTraffic;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addBtn1;
    private javax.swing.JButton addBtn2;
    private javax.swing.JComboBox<String> classCb;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel findTrainsBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JButton removeBtn;
    private javax.swing.JCheckBox termsConditionsCb;
    private javax.swing.JList<String> usersListL;
    // End of variables declaration//GEN-END:variables
    
}